GET http://localhost:3001/api/blogs

###
GET http://localhost:3001/api/authors

###
POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEwMzk0MzN9.t-q5niC3hH-lrO7rS3S4J_mxkNLspk9UKJb2SYySa_4

{
  "title": "Gang Bangers",
  "url": "rizvan.io",
  "author":"Rizvan",
  "likes": 100,
  "year": 2023
}

###
PUT http://localhost:3001/api/blogs/1
Content-Type: application/json

{
  "likes": 10
}

###
DELETE http://localhost:3001/api/blogs/3
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEwMzk0MzN9.t-q5niC3hH-lrO7rS3S4J_mxkNLspk9UKJb2SYySa_4

###
GET http://localhost:3001/api/users

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "name": "Rizvanas",
  "username": "rizvan@mail.com"
}




###
POST http://localhost:3001/api/readinglists
Content-Type: application/json

{
  "userId": 1,
  "blogId": 2
}

###
PUT http://localhost:3001/api/readinglists/6
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJpenZhbkBtYWlsLmNvbSIsImlkIjoxLCJpYXQiOjE3MDA5MjUyNzZ9.tt223vlTQjnu259pALMpPuM04OmihCiFsQsoN-Kqx5o

{
  "read": true
}

###
GET http://localhost:3001/api/readinglists

###
GET http://localhost:3001/api/users/1?read=true

###
GET http://localhost:3001/api/users/1

###
POST http://localhost:3001/api/login
Content-Type: application/json

{
  "username": "rizvan@mail.com",
  "password": "secret"
}

###
DELETE http://localhost:3001/api/logout
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MDEwNDA1NDN9.CRlClBU_hxL8qA4v6zPy1nheWCGp1qBKOq6ksVtcF1g