GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Testing things",
  "author":"Rizvan"
}

###
PUT http://localhost:3001/api/blogs/7
Content-Type: application/json

{
  "likess": 10
}

###
DELETE http://localhost:3001/api/blogs/6