GET http://localhost:3001/api/blogs

###
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "author":"Rizvan",
  "url":"rizvan.io",
  "title":"Blog addition test"
}

###
DELETE http://localhost:3001/api/blogs/3